### ISSUE TITLE
Adapt for use with Jest?

### ISSUE THREAD

**Issue by ethanroday** [hbenl/vscode-jasmine-test-adapter#20]
There is much interest in the main Test Explorer repo to have an adapter for Jest (https://github.com/hbenl/vscode-test-explorer/issues/14). Would it be straightforward to port this one or make it configurable, since Jest uses Jasmine under the hood?

**Comment by hbenl** [comment]
No, I've looked into this and found that a separate adapter would be needed because the main integration points (the API for starting a test run and the Reporter API) are both different. I've described the main challenges for writing a Jest adapter in the issue you linked to and hope that there is enough interest so that someone will start working on this.
